module:

  hugoVersion:
    extended: true
    min: '0.95.0'

  imports:
    - path: github.com/jquery/jquery-dist
      mounts:
        - source: dist/jquery.js
          target: assets/js/vendor/jquery.js
    - path: github.com/olivernn/lunr.js
      mounts:
        - source: lunr.js
          target: assets/js/vendor/lunr.js
    - path: github.com/MihaiValentin/lunr-languages
      mounts:
        - source: lunr.stemmer.support.js
          target: assets/js/vendor/lunr.stemmer.support.js
        - source: lunr.ru.js
          target: assets/js/vendor/lunr.multi.js
        - source: lunr.multi.js
          target: assets/js/vendor/lunr.ru.js
