name = "Ed"
license = "MIT"
licenselink = "https://github.com/sergeyklay/gohugo-theme-ed/blob/master/LICENSE"
description = "Ed theme for minimal editions"
homepage = "https://github.com/sergeyklay/gohugo-theme-ed"
tags = ["blog", "responsive", "light", "customizable", "minimal", "ed"]
features = ["posts"]
min_version = "0.84.0"

[author]
    name = "Serghei Iakovlev"
    homepage = "https://serghei.blog"

[original]
    author = "Alex Gil"
    homepage = "https://www.elotroalex.com"
    repo = "https://github.com/minicomp/ed"
