name = "Ed"
license = "MIT"
licenselink = "https://github.com/sergeyklay/gohugo-theme-ed/blob/master/LICENSE"
description = "Ed theme for minimal editions, based on Alex Gil theme"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/sergeyklay/gohugo-theme-ed/"

# If you have a running demo of the theme.
demosite = "https://sergeyklay.github.io/gohugo-theme-ed/"

tags = [
  "blog",
  "responsive",
  "simple",
  "clean",
  "light",
  "minimal",
  "minimalist",
  "customizable",
  "ed"
]

# The theme's features:
features = [
  "blog",
  "shortcodes",
  "responsive",
  "posts",
  "opengraph",
  "favicon",
  # "archive",
  # "search",
  "clean",
  "simple",
  "feed",
  "minimal",
  "minimalist",
  "mobile"
]

min_version = "0.84.0"

# If the theme has a single author.
[author]
  name = "Serghei Iakovlev"
  homepage = "https://serghei.blog/"

# If porting an existing theme.
[original]
  author = "Alex Gil"
  homepage = "https://www.elotroalex.com/"
  repo = "https://github.com/minicomp/ed/"
