baseURL = 'https://example.com/'

languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'Ed.'
theme = ['github.com/sergeyklay/gohugo-theme-ed']
resourceDir = '../resources'
enableRobotsTXT = true

# kick out RSS, we'll use Atom
disableKinds = ['RSS']

[outputs]
  # TODO:
  # home = [ "HTML", "Atom", "JSON", "humanstxt" ]
  # section = [ "HTML", "Atom" ]
  home = [ 'HTML', 'Atom', 'humanstxt' ]

# For more see: https://gohugo.io/templates/output-formats/
[outputFormats.humanstxt]
  mediaType = 'text/plain'
  baseName = 'humans'
  rel = 'author'
  isPlainText = true
  isHTML = false
  noUgly = true
  permalinkable = false

# Atom feed.
# For more see: https://validator.w3.org/feed/docs/atom.html#whatIsAtom
[outputFormats.Atom]
  name = 'Atom'
  # The correct header Content-Type header for an Atom feed is
  # application/atom+xml. However, Chromium does not handle it
  # correctly (see https://code.google.com/p/chromium/issues/detail?id=104358).
  #
  # The most compatible header is text/xml;charset=UTF-8, which
  # will cause the feed to be parsed correctly by most clients.
  # Note that you should be encoding your feed in UTF-8.
  mediaType = 'text/xml'
  # generated file = <baseName>.<mediaType.'text/xml'.suffixes[0]> = feeds/feed.atom.xml
  baseName = 'feeds/feed.atom'
  rel = 'alternate'
  isPlainText = false
  isHTML = false
  noUgly = true
  permalinkable = false

[mediaTypes]
  [mediaTypes.'text/xml']
    suffixes = ['xml']

[author]
  name = 'John Doe'
  email = 'john@example.com'
  github = '@john_doe'
  location = 'Kyiv, Ukraine'

[languages]
  [languages.en]
    weight = 1
    languageDirection = 'ltr'
    languageName = 'English'

[params]
  # Site description. Used in meta description
  description = 'Ed is a Hugo theme designed for textual editors based on minimal computing principles, and focused on legibility and flexibility.'
  # Copyright string
  copyright = 'Copyright (c) 2019 John Doe'
  # Color scheme. Options: red, orange, magenta, cyan, blue, brown
  colorScheme = ''
  # Used in site header
  tagline = 'a Hugo theme for minimal editions'
  # Custom footer text
  footer = ''
  # Sections to be displayed in the main page, as well as RSS/Atom feeds
  mainSections = ['posts', 'dramas', 'narratives', 'poems']
  # Order of post meta information
  postMeta = ['date']
  # Posts date format, for example: 2006-01-02
  dateformat = 'January 02, 2006'
  dateFormatFeed = '2006-01-02T15:04:05Z07:00'
  # Show "Read more" button in list if true
  readmore = true
  # RSS/Atom feed size
  feedSize = 25

  [params.assets]
    # Site icons, relative to ./static
    favicon = '' # favicon.ico for legacy browsers
    svgicon = '' # A single SVG icon with a light/dark version for modern browsers
    apple_touch_icon = '' # 180×180 PNG image for Apple devices
    webmanifest = '' # Web app manifest with 192×192 and 512×512 PNG icons for modern browsers

    logo = '/img/open-graph-logo.png' # Logo image, relative to ./assets
    logo_width = 200 # Logo image width
    logo_height = 200 # Logo image height

    disable_fingerprinting = false

[social]
  # Facebook Page Admin ID for Domain Insights
  facebook_admin = ''
  # Facebook Page ID
  facebook_id = ''

# For more see https://gohugo.io/content-management/menus/
[menu]
  [[menu.main]]         # sections in the website sidebar
    identifier = 'home' # section id
    name = 'Home'       # section display title
    url = '/'           # path to the section
    weight = 1          # order of sections
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 2
  [[menu.main]]
    identifier = 'credits'
    name = 'Credits'
    url = '/credits/'
    weight = 3
  [[menu.main]]
    identifier = 'documentation'
    name = 'Documentation'
    url = '/documentation/'
    weight = 4
  [[menu.main]]
    identifier = 'search'
    name = 'Search'
    url = '/search/' # TODO: Implement search
    weight = 5
  [[menu.main]]
    identifier = 'github'
    name = 'GitHub Project'
    url = 'https://github.com/sergeyklay/gohugo-theme-ed/'
    weight = 20
    [menu.main.params]
      external = true

# For more see https://gohugo.io/getting-started/configuration-markup/
[markup]
  defaultMarkdownHandler = 'goldmark'

  [markup.highlight]
    # Syntax highlight style.
    # For more see https://xyproto.github.io/splash/docs/
    style = 'emacs'

  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        # Enable custom attribute support for blocks
        block = true
