title = "Ed."
baseURL = "https://example.com"
languageCode = "en-us"
theme = ["github.com/sergeyklay/gohugo-theme-ed"]
resourceDir = "../resources"

defaultContentLanguage = "en"

[Author]
  name = "John Doe"

[languages]
  [languages.en]
    weight = 1
    # "rtl" for Right-To-Left languages
    languageDirection = "ltr"

[params]
  # Site description. Used in meta description
  description = "Ed is a Hugo theme designed for textual editors based on minimal computing principles, and focused on legibility and flexibility."
  # Color scheme. Options: red, orange, magenta, cyan, blue, brown
  color_scheme = ""
  # Github project url. Used in sidebar
  github_url = "https://github.com/sergeyklay/gohugo-theme-ed"
  # Used in site header
  tagline = "a Hugo theme for minimal editions"

[menu]
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.nav]]
    name = "Credits"
    url = "/credits/"
    weight = 2
  [[menu.nav]]
    name = "Documentation"
    url = "/documentation/"
    weight = 3

