baseURL = 'https://example.com/'

languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'Ed.'
theme = ['github.com/sergeyklay/gohugo-theme-ed']
resourceDir = '../resources'
enableRobotsTXT = true

[outputs]
  # TODO:
  # home = [ "HTML", "RSS", "Atom", "JSON", "humanstxt" ]
  # section = [ "HTML", "RSS", "Atom" ]
  home = [ 'HTML', 'humanstxt' ]

[outputFormats.humanstxt]
  baseName = 'humans'
  isPlainText = true
  mediaType = 'text/plain'

# TODO:
# [outputFormats.Atom]
# mediaType = "application/atom"
# baseName = "feed"
# isPlainText = false

# Possible 'Author' formats are:
#
# [author]
#     name = 'Foo Bar'
#     email = 'john@example.com'
#     github = '@john_doe'
#     location = 'Kyiv, Ukraine'
# ========= OR ===========
#
# [author]
#   [author.john_doe]
#     name = 'John Doe'
#     email = 'john@example.com'
#     github = '@john_doe'
#     location = 'Kyiv, Ukraine'
#   [author.jane_doe]
#     name = 'Jane Doe'
#     email = 'jane@example.com'
#     github = '@jane_doe'
#     location = 'Lviv, Ukraine'
[author]
  [author.john_doe]
    name = 'John Doe'
    email = 'john@example.com'
    github = '@john_doe'
    location = 'Kyiv, Ukraine'
  [author.jane_doe]
    name = 'Jane Doe'
    email = 'jane@example.com'
    github = '@jane_doe'
    location = 'Lviv, Ukraine'

[languages]
  [languages.en]
    weight = 1
    # "rtl" for Right-To-Left languages
    languageDirection = "ltr"

[params]
  # Site author name. For multiple authors use: ['Me', 'You']
  author = 'John Doe'
  # Site description. Used in meta description
  description = 'Ed is a Hugo theme designed for textual editors based on minimal computing principles, and focused on legibility and flexibility.'
  # Color scheme. Options: red, orange, magenta, cyan, blue, brown
  color_scheme = ''
  # Used in site header
  tagline = 'a Hugo theme for minimal editions'
  # Custom footer text
  footer = ''
  # Sections to be displayed in the main page
  main_sections = ['posts', 'dramas', 'narratives', 'poems']
  # Order of post meta information
  post_meta = ['date']
  # Posts date format, for example: 2006-01-02
  dateformat = 'January 02, 2006'
  # Show "Read more" button in list if true
  readmore = true

  [params.assets]
    # Site icons, relative to ./static
    favicon = '' # favicon.ico for legacy browsers
    svgicon = '' # A single SVG icon with a light/dark version for modern browsers
    apple_touch_icon = '' # 180×180 PNG image for Apple devices
    webmanifest = '' # Web app manifest with 192×192 and 512×512 PNG icons for modern browsers

    disable_fingerprinting = false

[social]
  # Facebook Page Admin ID for Domain Insights
  facebook_admin = ''
  # Facebook Page ID
  facebook_id = ''

# For more see https://gohugo.io/content-management/menus/
[menu]
  [[menu.main]]         # sections in the website sidebar
    identifier = 'home' # section id
    name = 'Home'       # section display title
    url = '/'           # path to the section
    weight = 1          # order of sections
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 2
  [[menu.main]]
    identifier = 'credits'
    name = 'Credits'
    url = '/credits/'
    weight = 3
  [[menu.main]]
    identifier = 'documentation'
    name = 'Documentation'
    url = '/documentation/'
    weight = 4
  [[menu.main]]
    identifier = 'search'
    name = 'Search'
    url = '/search/' # TODO: Implement search
    weight = 5
  [[menu.main]]
    identifier = 'github'
    name = 'GitHub Project'
    url = 'https://github.com/sergeyklay/gohugo-theme-ed/'
    weight = 20
    [menu.main.params]
      external = true

# For more see https://gohugo.io/getting-started/configuration-markup/
[markup]
  defaultMarkdownHandler = 'goldmark'

  [markup.highlight]
    # Syntax highlight style.
    # For more see https://xyproto.github.io/splash/docs/
    style = 'emacs'

  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        # Enable custom attribute support for blocks
        block = true
