name: CD

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "README.md"
    branches:
      - master
  workflow_dispatch:
    # manual run
    inputs:
      hugoVersion:
        description: "Hugo Version"
        required: false
        default: "0.84.0"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Build GH-Pages
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "${{ github.event.inputs.hugoVersion }}"

      - name: Build local ./exampleSite
        run: hugo --minify --gc --buildDrafts --verbose --destination ../public --source ./exampleSite --baseURL https://sergeyklay.github.io/gohugo-theme-ed/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
