name: CS

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'release/**'
      - 'fix/**'
    paths-ignore:
      - "README.md"
  # The branches below must be a subset of the branches above
  pull_request:
    branches:
      - master
    paths-ignore:
      - "README.md"

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    name: Code linting

    # The maximum number of minutes to let a workflow run
    # before GitHub automatically cancels it. Default: 360
    timeout-minutes: 30

    strategy:
      # When set to true, GitHub cancels
      # all in-progress jobs if any matrix job fails.
      fail-fast: false

      matrix:
        node:
          - '14.x'
        os:
          - ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
